ALTER TABLE DISPONIBILIDAD DROP FOREIGN KEY FKDISPONIBIL341981;

ALTER TABLE ACCESO DROP FOREIGN KEY accesa;

ALTER TABLE ALERGIA_MASCOTA DROP FOREIGN KEY alergia;

ALTER TABLE ALERGIA_MASCOTA DROP FOREIGN KEY alergias;

ALTER TABLE ALIMENTACION_MASCOTA DROP FOREIGN KEY alimento;

ALTER TABLE MEDICAMENTO_ESPECIE DROP FOREIGN KEY aplica;

ALTER TABLE DIRECCION_REFERENCIA DROP FOREIGN KEY asocia;

ALTER TABLE EMPLEADO_TIPO_SERVICIO DROP FOREIGN KEY atendido;

ALTER TABLE EMPLEADO_TIPO_SERVICIO DROP FOREIGN KEY atiende;

ALTER TABLE CARTILLA_MASCOTAS DROP FOREIGN KEY cartilla;

ALTER TABLE CITA_SERVICIO DROP FOREIGN KEY cita;

ALTER TABLE ALIMENTACION_MASCOTA DROP FOREIGN KEY come;

ALTER TABLE NUMERO_CONTACTO_CLIENTES DROP FOREIGN KEY contacta;

ALTER TABLE CUARTO DROP FOREIGN KEY contiene;

ALTER TABLE CORREO_ALTERNATIVO DROP FOREIGN KEY `correo electronico`;

ALTER TABLE DISPONIBILIDAD DROP FOREIGN KEY `dispone de`;

ALTER TABLE MASCOTA DROP FOREIGN KEY dueno;

ALTER TABLE PLANTILLA_EMPLEADOS DROP FOREIGN KEY emplea;

ALTER TABLE PLANTILLA_EMPLEADOS DROP FOREIGN KEY `es empleado por`;

ALTER TABLE RAZA DROP FOREIGN KEY especifica;

ALTER TABLE CARTILLA_MASCOTAS DROP FOREIGN KEY incluye;

ALTER TABLE TIPO_CUARTO DROP FOREIGN KEY `puede hospedar`;

ALTER TABLE MASCOTA DROP FOREIGN KEY raza;

ALTER TABLE MEDICAMENTO_ESPECIE DROP FOREIGN KEY `se le aplica`;

ALTER TABLE CITA_SERVICIO DROP FOREIGN KEY solicita;

ALTER TABLE CUARTO DROP FOREIGN KEY tipo;

ALTER TABLE CATALOGO_VACUNAS DROP FOREIGN KEY vacunas;

DROP TABLE IF EXISTS ACCESO;

DROP TABLE IF EXISTS ALERGIA;

DROP TABLE IF EXISTS ALERGIA_MASCOTA;

DROP TABLE IF EXISTS ALIMENTACION_MASCOTA;

DROP TABLE IF EXISTS CARTILLA_MASCOTAS;

DROP TABLE IF EXISTS CATALOGO_ALIMENTOS;

DROP TABLE IF EXISTS CATALOGO_VACUNAS;

DROP TABLE IF EXISTS CITA_SERVICIO;

DROP TABLE IF EXISTS CLIENTE;

DROP TABLE IF EXISTS CORREO_ALTERNATIVO;

DROP TABLE IF EXISTS CUARTO;

DROP TABLE IF EXISTS DIRECCION_REFERENCIA;

DROP TABLE IF EXISTS DISPONIBILIDAD;

DROP TABLE IF EXISTS EMPLEADO;

DROP TABLE IF EXISTS EMPLEADO_TIPO_SERVICIO;

DROP TABLE IF EXISTS ESPECIE;

DROP TABLE IF EXISTS MASCOTA;

DROP TABLE IF EXISTS MEDICAMENTO;

DROP TABLE IF EXISTS MEDICAMENTO_ESPECIE;

DROP TABLE IF EXISTS NUMERO_CONTACTO_CLIENTES;

DROP TABLE IF EXISTS PLANTILLA_EMPLEADOS;

DROP TABLE IF EXISTS RAZA;

DROP TABLE IF EXISTS SUCURSAL;

DROP TABLE IF EXISTS TIPO_CUARTO;

DROP TABLE IF EXISTS TIPO_SERVICIO;

-- Creación de tablas y restricciones
CREATE TABLE ACCESO (
    CORREO_ELECTRONICO_PRIMARIO varchar(255) NOT NULL,
    CLIENTES_ID_CLIENTE int(10) NOT NULL,
    CONTRASEÑA varchar(255),
    PRIMARY KEY (CORREO_ELECTRONICO_PRIMARIO)
);

CREATE TABLE ALERGIA (
    ID_ALERGIA int(10) NOT NULL AUTO_INCREMENT,
    OBJETO_ALERGIA varchar(20),
    PRIMARY KEY (ID_ALERGIA)
);

CREATE TABLE ALERGIA_MASCOTA (
    MASCOTASID_MASCOTA int(10) NOT NULL,
    CATALOGO_ALERGIASID_ALERGIA int(10) NOT NULL,
    PRIMARY KEY (
        MASCOTASID_MASCOTA,
        CATALOGO_ALERGIASID_ALERGIA
    )
);

CREATE TABLE ALIMENTACION_MASCOTA (
    CATALOGO_ALIMENTOSID_ALIMENTO int(10) NOT NULL,
    MASCOTASID_MASCOTA int(10) NOT NULL,
    PRIMARY KEY (
        CATALOGO_ALIMENTOSID_ALIMENTO,
        MASCOTASID_MASCOTA
    )
);

CREATE TABLE CARTILLA_MASCOTAS (
    ID_MASCOTA int(10) NOT NULL,
    ID_MEDICAMENTO int(10) NOT NULL,
    FECHA_ULTIMA_APLICACION date,
    NOMBRE_ESPECIE varchar(10) NOT NULL,
    `CATALOGO_VACUNASMEDICAMENTO_ESPECIEESPECIEID_ESPECIE int` int(11) NOT NULL,
    PRIMARY KEY (
        ID_MASCOTA,
        ID_MEDICAMENTO,
        NOMBRE_ESPECIE,
        `CATALOGO_VACUNASMEDICAMENTO_ESPECIEESPECIEID_ESPECIE int`
    )
);

CREATE TABLE CATALOGO_ALIMENTOS (
    ID_ALIMENTO int(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_ALIMENTO varchar(1000),
    DESCRIPCION varchar(4000),
    PRIMARY KEY (ID_ALIMENTO)
);

CREATE TABLE CATALOGO_VACUNAS (
    ID_MEDICAMENTO int(10) NOT NULL,
    ENFERMEDAD_A_TRATAR varchar(50),
    PERIODO_EFECTIVO date,
    `MEDICAMENTO_ESPECIEESPECIEID_ESPECIE int` int(11) NOT NULL,
    PRIMARY KEY (
        ID_MEDICAMENTO,
        `MEDICAMENTO_ESPECIEESPECIEID_ESPECIE int`
    )
);

CREATE TABLE CITA_SERVICIO (
    ID_CITA int(10) NOT NULL AUTO_INCREMENT,
    EMERGENTE bit(1),
    PRECIO_CITA int(10),
    ID_CUARTO int(10) NOT NULL,
    EMPLEADO_TIPO_SERVICIOEMPLEADOID_EMPLEADO int(10) NOT NULL,
    EMPLEADO_TIPO_SERVICIOTIPO_SERVICIOID_SERVICIO int(10) NOT NULL,
    PRIMARY KEY (ID_CITA)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE int(10) NOT NULL AUTO_INCREMENT,
    CURP varchar(18),
    NOMBRES_CLIENTES varchar(50),
    PRIMER_APELLIDO varchar(90),
    SEGUNDO_APELLIDO varchar(90),
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CORREO_ALTERNATIVO (
    CORREO_ELECTRONICO varchar(255),
    CLIENTES_ID_CLIENTE int(10) NOT NULL,
    PRIMARY KEY (CLIENTES_ID_CLIENTE)
);

CREATE TABLE CUARTO (
    ID_CUARTO int(10) NOT NULL AUTO_INCREMENT,
    NUMERO_CUARTO int(10),
    ID_TIPO_CUARTO int(10) NOT NULL,
    ID_SUCURSAL int(10) NOT NULL,
    PRIMARY KEY (ID_CUARTO)
);

CREATE TABLE DIRECCION_REFERENCIA (
    CALLE_REFERENCIA varchar(255),
    NUMERO_CALLE_REFERENCIA varchar(255),
    NOMBRE_COLONIA_REFERENCIA varchar(255),
    NOMBRE_MUNICIPIO_REFERENCIA varchar(255),
    CODIGO_POSTAL_REFERENCIA int(5),
    ENTIDAD_REFERENCIA varchar(255),
    CLIENTES_ID_CLIENTE int(10) NOT NULL,
    PRIMARY KEY (CLIENTES_ID_CLIENTE)
);

CREATE TABLE DISPONIBILIDAD (
    ID_CUARTO int(10) NOT NULL,
    FECHA_OCUPABILIDAD date,
    OCUPADA bit(1),
    CHECK_IN bit(1),
    CHECK_OUT bit(1),
    MASCOTAID_MASCOTA int(10) NOT NULL,
    PRIMARY KEY (ID_CUARTO)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO int(10) NOT NULL AUTO_INCREMENT,
    NOMBRES varchar(255),
    PRIMER_APELLIDO_EMPLEADO varchar(255),
    SEGUNDO_APELLIDO_EMPLEADO varchar(255),
    PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE EMPLEADO_TIPO_SERVICIO (
    EMPLEADOID_EMPLEADO int(10) NOT NULL,
    TIPO_SERVICIOID_SERVICIO int(10) NOT NULL,
    PRIMARY KEY (
        EMPLEADOID_EMPLEADO,
        TIPO_SERVICIOID_SERVICIO
    )
);

CREATE TABLE ESPECIE (
    NOMBRE_ESPECIE varchar(10) NOT NULL,
    ID_ESPECIE int(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_ESPECIE)
);

CREATE TABLE MASCOTA (
    ID_MASCOTA int(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_MASCOTA varchar(50),
    FECHA_NACIMIENTO date,
    CRUAC int(10),
    ID_TAMANO int(10),
    FOTOGRAFIA varbinary(2000),
    CONDICIONES_CONDUCTUALES longtext,
    CONDICIONES_FISICAS longtext,
    CLIENTEID_CLIENTE int(10) NOT NULL,
    RAZAID_RAZA int(11) NOT NULL,
    PRIMARY KEY (ID_MASCOTA)
);

CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO int(10) NOT NULL AUTO_INCREMENT,
    RAZON_SOCIAL varchar(70),
    NOMBRE_MEDICAMENTO varchar(70),
    NUMERO_REGISTRO varchar(11),
    PRIMARY KEY (ID_MEDICAMENTO)
);

CREATE TABLE MEDICAMENTO_ESPECIE (
    ID_MEDICAMENTO int(10) NOT NULL,
    ESPECIEID_ESPECIE int(11) NOT NULL,
    PRIMARY KEY (
        ID_MEDICAMENTO,
        ESPECIEID_ESPECIE
    )
);

CREATE TABLE NUMERO_CONTACTO_CLIENTES (
    NUMERO_TELEFONICO_CIENTES int(10) NOT NULL,
    CLIENTES_ID_CLIENTE int(10) NOT NULL,
    PRIMARY KEY (
        NUMERO_TELEFONICO_CIENTES,
        CLIENTES_ID_CLIENTE
    )
);

CREATE TABLE PLANTILLA_EMPLEADOS (
    SUCURSALES_ID_SUCURSAL int(10) NOT NULL,
    EMPLEADOS_ID_EMPLEADO int(10) NOT NULL,
    PRIMARY KEY (
        SUCURSALES_ID_SUCURSAL,
        EMPLEADOS_ID_EMPLEADO
    )
);

CREATE TABLE RAZA (
    NOMBRE_RAZA varchar(10) NOT NULL,
    ESPECIEID_ESPECIE int(11) NOT NULL,
    ID_RAZA int(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_RAZA)
);

CREATE TABLE SUCURSAL (
    ID_SUCURSAL int(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_SUCURSAL varchar(255) UNIQUE,
    CALLE_DIRECCION varchar(255),
    NUMERO_DIRECCION varchar(255),
    NOMBRE_COLONIA_DIRECCION varchar(255),
    NOMBRE_MUNICIPIO_DIRECCION varchar(255),
    CODIGO_POSTAL_DIRECCION int(5),
    ENTIDAD_DIRECCION varchar(255),
    PRIMARY KEY (ID_SUCURSAL)
);

CREATE TABLE TIPO_CUARTO (
    ID_TIPO_CUARTO int(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_CUARTO varchar(10),
    PRECIO_CUARTO int(10) NOT NULL,
    ESPECIEID_ESPECIE int(11) NOT NULL,
    PRIMARY KEY (ID_TIPO_CUARTO)
);

CREATE TABLE TIPO_SERVICIO (
    ID_SERVICIO int(10) NOT NULL AUTO_INCREMENT,
    NOMBRE_SERVICIO varchar(50),
    COSTO_BASE int(10),
    COSTO_EXTRA int(10),
    PRIMARY KEY (ID_SERVICIO)
);

ALTER TABLE DISPONIBILIDAD
ADD CONSTRAINT FKDISPONIBIL341981 FOREIGN KEY (MASCOTAID_MASCOTA) REFERENCES MASCOTA (ID_MASCOTA);

ALTER TABLE ACCESO
ADD CONSTRAINT accesa FOREIGN KEY (CLIENTES_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE ALERGIA_MASCOTA
ADD CONSTRAINT alergia FOREIGN KEY (CATALOGO_ALERGIASID_ALERGIA) REFERENCES ALERGIA (ID_ALERGIA);

ALTER TABLE ALERGIA_MASCOTA
ADD CONSTRAINT alergias FOREIGN KEY (MASCOTASID_MASCOTA) REFERENCES MASCOTA (ID_MASCOTA);

ALTER TABLE ALIMENTACION_MASCOTA
ADD CONSTRAINT alimento FOREIGN KEY (CATALOGO_ALIMENTOSID_ALIMENTO) REFERENCES CATALOGO_ALIMENTOS (ID_ALIMENTO);

ALTER TABLE MEDICAMENTO_ESPECIE
ADD CONSTRAINT aplica FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO (ID_MEDICAMENTO);

ALTER TABLE DIRECCION_REFERENCIA
ADD CONSTRAINT asocia FOREIGN KEY (CLIENTES_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE EMPLEADO_TIPO_SERVICIO
ADD CONSTRAINT atendido FOREIGN KEY (TIPO_SERVICIOID_SERVICIO) REFERENCES TIPO_SERVICIO (ID_SERVICIO);

ALTER TABLE EMPLEADO_TIPO_SERVICIO
ADD CONSTRAINT atiende FOREIGN KEY (EMPLEADOID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO);

ALTER TABLE CARTILLA_MASCOTAS
ADD CONSTRAINT cartilla FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA (ID_MASCOTA);

ALTER TABLE CITA_SERVICIO
ADD CONSTRAINT cita FOREIGN KEY (
    EMPLEADO_TIPO_SERVICIOEMPLEADOID_EMPLEADO,
    EMPLEADO_TIPO_SERVICIOTIPO_SERVICIOID_SERVICIO
) REFERENCES EMPLEADO_TIPO_SERVICIO (
    EMPLEADOID_EMPLEADO,
    TIPO_SERVICIOID_SERVICIO
);

ALTER TABLE ALIMENTACION_MASCOTA
ADD CONSTRAINT come FOREIGN KEY (MASCOTASID_MASCOTA) REFERENCES MASCOTA (ID_MASCOTA);

ALTER TABLE NUMERO_CONTACTO_CLIENTES
ADD CONSTRAINT contacta FOREIGN KEY (CLIENTES_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE CUARTO
ADD CONSTRAINT contiene FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);

ALTER TABLE CORREO_ALTERNATIVO
ADD CONSTRAINT `correo electronico` FOREIGN KEY (CLIENTES_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE DISPONIBILIDAD
ADD CONSTRAINT `dispone de` FOREIGN KEY (ID_CUARTO) REFERENCES CUARTO (ID_CUARTO);

ALTER TABLE MASCOTA
ADD CONSTRAINT dueno FOREIGN KEY (CLIENTEID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE PLANTILLA_EMPLEADOS
ADD CONSTRAINT emplea FOREIGN KEY (SUCURSALES_ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);

ALTER TABLE PLANTILLA_EMPLEADOS
ADD CONSTRAINT `es empleado por` FOREIGN KEY (EMPLEADOS_ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO);

ALTER TABLE RAZA
ADD CONSTRAINT especifica FOREIGN KEY (ESPECIEID_ESPECIE) REFERENCES ESPECIE (ID_ESPECIE);

ALTER TABLE CARTILLA_MASCOTAS
ADD CONSTRAINT incluye FOREIGN KEY (
    ID_MEDICAMENTO,
    `CATALOGO_VACUNASMEDICAMENTO_ESPECIEESPECIEID_ESPECIE int`
) REFERENCES CATALOGO_VACUNAS (
    ID_MEDICAMENTO,
    `MEDICAMENTO_ESPECIEESPECIEID_ESPECIE int`
);

ALTER TABLE TIPO_CUARTO
ADD CONSTRAINT `puede hospedar` FOREIGN KEY (ESPECIEID_ESPECIE) REFERENCES ESPECIE (ID_ESPECIE);

ALTER TABLE MASCOTA
ADD CONSTRAINT raza FOREIGN KEY (RAZAID_RAZA) REFERENCES RAZA (ID_RAZA);

ALTER TABLE MEDICAMENTO_ESPECIE
ADD CONSTRAINT `se le aplica` FOREIGN KEY (ESPECIEID_ESPECIE) REFERENCES ESPECIE (ID_ESPECIE);

ALTER TABLE CITA_SERVICIO
ADD CONSTRAINT solicita FOREIGN KEY (ID_CUARTO) REFERENCES DISPONIBILIDAD (ID_CUARTO);

ALTER TABLE CUARTO
ADD CONSTRAINT tipo FOREIGN KEY (ID_TIPO_CUARTO) REFERENCES TIPO_CUARTO (ID_TIPO_CUARTO);

ALTER TABLE CATALOGO_VACUNAS
ADD CONSTRAINT vacunas FOREIGN KEY (
    ID_MEDICAMENTO,
    `MEDICAMENTO_ESPECIEESPECIEID_ESPECIE int`
) REFERENCES MEDICAMENTO_ESPECIE (
    ID_MEDICAMENTO,
    ESPECIEID_ESPECIE
);

-- Población de tablas
INSERT INTO
    SUCURSAL (
        NOMBRE_SUCURSAL,
        CALLE_DIRECCION,
        NUMERO_DIRECCION,
        NOMBRE_COLONIA_DIRECCION,
        NOMBRE_MUNICIPIO_DIRECCION,
        CODIGO_POSTAL_DIRECCION,
        ENTIDAD_DIRECCION
    )
VALUES (
        'Ciudad de México',
        'Calle Reforma',
        123,
        'Centro',
        'Cuauhtémoc',
        06500,
        'CDMX'
    ),
    (
        'Guadalajara',
        'Avenida Juárez',
        456,
        'Americana',
        'Guadalajara',
        44100,
        'Jalisco'
    ),
    (
        'Monterrey',
        'Calle Morelos',
        789,
        'Centro',
        'Monterrey',
        64000,
        'Nuevo León'
    );

INSERT INTO
    ESPECIE (NOMBRE_ESPECIE)
VALUES ('Lagarto'),
    ('Perro'),
    ('Gato');

INSERT INTO
    RAZA (
        NOMBRE_RAZA,
        ESPECIEID_ESPECIE
    )
VALUES ('Iguana', 1),
    ('Gecko', 1),
    ('Camaleón', 1),
    ('Dragón Barbudo', 1),
    ('Anolis', 1),
    ('Labrador Retriever', 2),
    ('Bulldog', 2),
    ('Pastor Alemán', 2),
    ('Poodle', 2),
    ('Beagle', 2),
    ('Siamés', 3),
    ('Persa', 3),
    ('Maine Coon', 3),
    ('Bengalí', 3),
    ('Sphynx', 3);