-- CREAR TABLAS

-- MEDICAMENTOS
CREATE TABLE MEDICAMENTOS(
    ID_MEDICAMENTO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    REGISTRO VARCHAR(20) NOT NULL,
    LABORATORIO VARCHAR(40) NOT NULL,
    NOMBRE_MEDICAMENTO VARCHAR(100) NOT NULL
);

-- CARTILLA DE MASCOTAS
DROP TABLE CARTILLA_MASCOTAS CASCADE;

CREATE TABLE CARTILLA_MASCOTAS(
    ID_MASCOTA INT UNSIGNED PRIMARY KEY,
    ID_MEDICAMENTOS INT UNSIGNED NOT NULL,
    ULTIMA_DOSIS_APLICADA DATE NOT NULL
);

-- MEDICAMENTOS RECETADOS
CREATE TABLE MEDICAMENTOS_RECETADOS(
    ID_MASCOTA INT  UNSIGNED PRIMARY KEY,
    ID_MEDICAMENTOS INT UNSIGNED NOT NULL,
    DOSIS_FALTANTES INT UNSIGNED NOT NULL,
    FRECUENCIA_APLICACION VARCHAR(200),
    ULTIMA_DOSIS_APLICADA DATE
);

-- CATÁLOGO DE ALIMENTOS
CREATE TABLE CATALOGO_ALIMENTOS(
    ID_ALIMENTOS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ALIMENTO VARCHAR(50) NOT NULL,
    DESCRIPCION_ALIMENTO VARCHAR(100) NOT NULL
);
-- CUIDADOS RUTINARIOS
CREATE TABLE CUIDADOS_RUTINARIOS(
    ID_MASCOTA INT UNSIGNED PRIMARY KEY,
    ID_ALIMENTOS INT UNSIGNED NOT NULL,
    ALERGIAS VARCHAR(255),
    CONDICIONES_ESPECIALES VARCHAR(255)
);

-- ESPECIES
CREATE TABLE ESPECIES(
    NOMBRE_ESPECIE VARCHAR(50) PRIMARY KEY,
    DESCRIPCION VARCHAR(255)
);

-- RAZAS
CREATE TABLE RAZAS(
    NOMBRE_RAZA VARCHAR(100) PRIMARY KEY,
    NOMBRE_ESPECIE VARCHAR(50) NOT NULL
);

-- MASCOTAS
CREATE TABLE MASCOTAS(
    ID_MASCOTA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_RAZA VARCHAR(100) NOT NULL,
    NOMBRE_MASCOTA VARCHAR(100) NOT NULL,
    TAMANO ENUM("Pequeño", "Mediano", "Grande") NOT NULL,
    FECHA_NACIMIENTO DATE,
    COLOR VARCHAR(20)
);

-- CLIENTES
CREATE TABLE CLIENTES(
    CURP VARCHAR(19) PRIMARY KEY,
    NOMBRES TINYTEXT,
    PRIMER_APELLIDO TINYTEXT,
    SEGUNDO_APELLIDO TINYTEXT 
);

-- NÚMEROS TELEFÓNICOS
DROP TABLE NUMEROS_TELEFONICOS CASCADE;

CREATE TABLE NUMEROS_TELEFONICOS(
    CURP VARCHAR(19),
    NUMERO_TELEFONICO INT UNSIGNED PRIMARY KEY
);

-- CORREOS ELECTRÓNICOS
DROP TABLE CORREOS_ELECTRONICOS CASCADE;

CREATE TABLE CORREOS_ELECTRONICOS(
    CURP VARCHAR(19),
    CORREO_ELECTRONICO VARCHAR(100) PRIMARY KEY
);

-- DIRECCIONES DE REFERENCIA
DROP TABLE DIRECCIONES_REFERENCIA CASCADE;

CREATE TABLE DIRECCIONES_REFERENCIA(
    CURP VARCHAR(19) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO_EXTERIOR INT UNSIGNED NOT NULL,
    NUMERO_INTERIOR INT UNSIGNED,
    COLONIA TINYTEXT NOT NULL,
    CODIGO_POSTAL INT UNSIGNED NOT NULL,
    MUNICIPIO_ALCALDIA TINYTEXT NOT NULL,
    ESTADO TINYTEXT NOT NULL
);

-- RESERVACIÓN
CREATE TABLE RESERVACION(
    ID_RESERVACION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_MASCOTA INT UNSIGNED NOT NULL,
    CURP VARCHAR(19) NOT NULL
);

-- CATÁLOGO DE CUARTOS
CREATE TABLE CATALOGO_CUARTOS(
    ID_TIPO_CUARTO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CUARTO VARCHAR(50) NOT NULL,
    TAMANO ENUM("Pequeño", "Mediano", "Grande") NOT NULL,
    PRECIO_CUARTO INT UNSIGNED NOT NULL
);

-- SUCURSALES
CREATE TABLE SUCURSALES(
    ID_SUCURSAL INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CIUDAD_UBICACION TINYTEXT NOT NULL
);

-- CUARTOS
CREATE TABLE CUARTOS(
    ID_CUARTO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_TIPO_CUARTO INT UNSIGNED NOT NULL,
    ID_SUCURSAL INT UNSIGNED NOT NULL,
    NUMERO_CUARTO VARCHAR(10) NOT NULL
);

-- HOSPEDAJE
DROP TABLE HOSPEDAJE;
CREATE TABLE HOSPEDAJE(
    ID_HOSPEDAJE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_RESERVACION INT UNSIGNED NOT NULL,
    ID_CUARTO INT UNSIGNED NOT NULL,
    CHECK_IN DATETIME NOT NULL,
    CHECK_OUT DATETIME NOT NULL,
    TOTAL_SERVICIOS INT UNSIGNED NOT NULL,
    TOTAL_CUARTO INT UNSIGNED NOT NULL,
    CORTE INT UNSIGNED NOT NULL,
    EQUIPAJE_TRANSPORTE BOOLEAN NOT NULL DEFAULT 0
);

-- RESEÑAS DEL HOTEL
CREATE TABLE RESENAS_HOTEL(
    ID_RESENA_HOTEL INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_SUCURSAL INT UNSIGNED NOT NULL,
    ID_HOSPEDAJE INT UNSIGNED NOT NULL,
    DESCRIPCION TINYTEXT NOT NULL,
    CALIFICACION FLOAT(3,2) UNSIGNED NOT NULL 
);

-- EMPLEADOS DE TODAS LAS SUCURSALES
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRES TINYTEXT NOT NULL,
    PRIMER_APELLIDO TINYTEXT NOT NULL,
    SEGUNDO_APELLIDO TINYTEXT NOT NULL,
    NUMERO_CONTACTO INT UNSIGNED NOT NULL
);

-- EMPLEADOS POR SUCURSALES
DROP TABLE SUC_EMP CASCADE;
CREATE TABLE SUC_EMP(
    ID_SUCURSAL INT UNSIGNED NOT NULL,
    ID_EMPLEADO INT UNSIGNED NOT NULL
);

-- CATÁLOGO DE SERVICIOS
CREATE TABLE CATALOGO_SERVICIOS(
    ID_SERVICIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_SERVICIO TINYTEXT NOT NULL,
    COSTO_BASE INT UNSIGNED NOT NULL,
    COSTO_EXTRA INT UNSIGNED
);

-- CITAS POR AGENDAR
CREATE TABLE CITAS(
    ID_CITA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HOSPEDAJE INT UNSIGNED NOT NULL,
    ID_SERVICIO INT UNSIGNED NOT NULL,
    ID_EMPLEADO INT UNSIGNED NOT NULL,
    FECHA_CITA DATETIME NOT NULL,
    COSTO_TOTAL INT UNSIGNED NOT NULL
);

-- RESEÑAS DE LOS SERVICIOS CON CITA DE LOS CLIENTES
CREATE TABLE RESENAS_CITAS(
    ID_RESENA_CITA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_CITA INT UNSIGNED NOT NULL,
    ID_HOSPEDAJE INT UNSIGNED NOT NULL,
    CALIFICACION INT UNSIGNED,
    DESCRIPCION VARCHAR(255)
);



-- AGREGANDO LAS LLAVES FORÁNEAS
-- CARTILLA DE MASCOTAS
ALTER TABLE CARTILLA_MASCOTAS
ADD CONSTRAINT ID_MASCOTA_FK FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA);
ALTER TABLE CARTILLA_MASCOTAS
ADD CONSTRAINT ID_MEDICAMENTO_FK FOREIGN KEY (ID_MEDICAMENTOS) REFERENCES MEDICAMENTOS(ID_MEDICAMENTO);

-- MEDICAMENTOS RECETADOS
ALTER TABLE MEDICAMENTOS_RECETADOS
ADD CONSTRAINT ID_MASCOTA_MEDICAMENTOS_RECETADOS_FK FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA);

ALTER TABLE MEDICAMENTOS_RECETADOS
ADD CONSTRAINT ID_MEDICAMENTOS_MEDICAMENTOS_RECETADOS_FK FOREIGN KEY (ID_MEDICAMENTOS) REFERENCES MEDICAMENTOS(ID_MEDICAMENTO);

-- CUIDADOS RUTINARIOS
ALTER TABLE CUIDADOS_RUTINARIOS
ADD CONSTRAINT ID_MASCOTA_CUIDADOS_RUTINARIOS_FK FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA);

ALTER TABLE CUIDADOS_RUTINARIOS
ADD CONSTRAINT ID_ALIMENTOS_CUIDADOS_RUTINARIOS_FK FOREIGN KEY (ID_ALIMENTOS) REFERENCES CATALOGO_ALIMENTOS(ID_ALIMENTOS);

-- RAZAS
ALTER TABLE RAZAS
ADD CONSTRAINT NOMBRE_ESPECIE_RAZAS_FK FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIES(NOMBRE_ESPECIE);

-- MASCOTAS
ALTER TABLE MASCOTAS
ADD CONSTRAINT NOMBRE_RAZA_MASCOTAS_FK FOREIGN KEY (NOMBRE_RAZA) REFERENCES RAZAS(NOMBRE_RAZA);

-- NÚMEROS TELEFÓNICOS
ALTER TABLE NUMEROS_TELEFONICOS
ADD CONSTRAINT CURP_NUMEROS_TELEFONICO_FK FOREIGN KEY (CURP) REFERENCES CLIENTES(CURP);

-- CORREOS ELECTRÓNICOS
ALTER TABLE CORREOS_ELECTRONICOS
ADD CONSTRAINT CURP_CORREOS_ELECTRONICOS_FK FOREIGN KEY (CURP) REFERENCES CLIENTES(CURP);

-- DIRECCIONES DE REFERENCIA
ALTER TABLE DIRECCIONES_REFERENCIA
ADD CONSTRAINT CURP_DIRECCIONES_REFERENCIA_FK FOREIGN KEY (CURP) REFERENCES CLIENTES(CURP);

ALTER TABLE DIRECCIONES_REFERENCIA
ADD PRIMARY KEY(CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, CODIGO_POSTAL)

-- RESERVACIÓN
ALTER TABLE RESERVACION
ADD CONSTRAINT ID_MASCOTAS_RESERVACION_FK FOREIGN KEY (ID_MASCOTAS) REFERENCES MASCOTAS(ID_MASCOTAS);

ALTER TABLE RESERVACION
ADD CONSTRAINT CURP_RESERVACION_FK FOREIGN KEY (CURP) REFERENCES CLIENTES(CURP);

-- CUARTOS
ALTER TABLE CUARTOS
ADD CONSTRAINT ID_TIPO_CUARTO_CUARTOS_FK FOREIGN KEY (ID_TIPO_CUARTO) REFERENCES CATALOGO_CUARTOS(ID_TIPO_CUARTO);

ALTER TABLE CUARTOS
ADD CONSTRAINT ID_SUCURSAL_CUARTOS_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL);

-- HOSPEDAJE
ALTER TABLE HOSPEDAJE
ADD CONSTRAINT ID_RESERVACION_HOSPEDAJE_FK FOREIGN KEY (ID_RESERVACION) REFERENCES RESERVACION(ID_RESERVACION);

ALTER TABLE HOSPEDAJE
ADD CONSTRAINT ID_CUARTO_HOSPEDAJE_FK FOREIGN KEY (ID_CUARTO) REFERENCES CUARTOS(ID_CUARTO);

-- RESEÑAS DEL HOTEL
ALTER TABLE RESENAS_HOTEL
ADD CONSTRAINT ID_SUCURSAL_RESENAS_HOTEL_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL);

ALTER TABLE RESENAS_HOTEL
ADD CONSTRAINT ID_HOSPEDAJE_RESENAS_HOTEL_FK FOREIGN KEY (ID_HOSPEDAJE) REFERENCES HOSPEDAJE(ID_HOSPEDAJE);

-- EMPLEADOS POR SUCURSALES
ALTER TABLE SUC_EMP
ADD CONSTRAINT ID_SUCURSAL_SUC_EMP_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL);

ALTER TABLE SUC_EMP
ADD CONSTRAINT ID_EMPLEADO_SUC_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO);

-- CITAS POR AGENDAR
ALTER TABLE CITAS
ADD CONSTRAINT ID_HOSPEDAJE_CITAS_FK FOREIGN KEY (ID_HOSPEDAJE) REFERENCES HOSPEDAJE(ID_HOSPEDAJE);

ALTER TABLE CITAS
ADD CONSTRAINT ID_SERVICIO_CITAS_FK FOREIGN KEY (ID_SERVICIO) REFERENCES CATALOGO_SERVICIOS(ID_SERVICIO);

ALTER TABLE CITAS
ADD CONSTRAINT ID_EMPLEADO_CITAS_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO);

-- RESEÑAS DE LOS SERVICIOS CON CITA DE LOS CLIENTES
ALTER TABLE RESENAS_CITAS
ADD CONSTRAINT ID_CITA_RESENAS_CITAS_FK FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA);

ALTER TABLE RESENAS_CITAS
ADD CONSTRAINT ID_HOSPEDAJE_RESENAS_CITAS_FK FOREIGN KEY (ID_HOSPEDAJE) REFERENCES HOSPEDAJE(ID_HOSPEDAJE);